version: "3.7"

services:


  redis:
    container_name: redis_dev_container
    image: redis
    ports:
      - "6379:6379"
  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    image: postgres:latest
    networks:
      - default
    ports:
      - 5406:5432
    restart: always
    volumes:
      - database_postgres:/var/lib/postgresql/data

  django_service:
    container_name: travel_huxy_container
    restart: always
    image: drf

    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis
      - db
    ports:
      - '5005:5005'
    volumes:
      - ./:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DB_NAME=test
      - DEBUG_CONFIG=false
      - DB_USER=test
      - DB_PASSWORD=test
      - DB_HOST=test
      - SECRET_KEY=huxy
      - DB_PORT=5432
      - DB_TEST=test
      - WEATHER_BASE_URL=api.openweathermap.org/data/2.5/forecast
      - WEATHER_API_KEY=1d4ce67223a53a013fc03ead36137396
      - CITIES_URL=https://raw.githubusercontent.com/huxaiphaer/travel_huxy/master/app/static/data/current_city_list.json
      - DB_TEST=tests

volumes:
  database_postgres: